// ava3 telemtry message definition

// @generated by protoc-gen-es v1.10.1
// @generated from file proto/ava3.proto (package ava3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message ava3.Telemetry
 */
export const Telemetry = /*@__PURE__*/ proto3.makeMessageType(
  "ava3.Telemetry",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

