// ava3 telemtry message definition

// @generated by protoc-gen-es v1.10.1
// @generated from file proto/ava3.proto (package ava3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message ava3.Telemetry
 */
export declare class Telemetry extends Message<Telemetry> {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string timestamp = 2;
   */
  timestamp: string;

  /**
   * @generated from field: uint32 id = 3;
   */
  id: number;

  /**
   * @generated from field: repeated string data = 4;
   */
  data: string[];

  constructor(data?: PartialMessage<Telemetry>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ava3.Telemetry";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Telemetry;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Telemetry;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Telemetry;

  static equals(a: Telemetry | PlainMessage<Telemetry> | undefined, b: Telemetry | PlainMessage<Telemetry> | undefined): boolean;
}

